apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-postech-fastfood-orquestrador
  namespace: fiap-pos-tech
spec:
  selector:
    matchLabels:
      app: fiap-postech-fastfood-orquestrador
  replicas: 1
  template:
    metadata:
      labels:
        app: fiap-postech-fastfood-orquestrador
    spec:
      containers:
        - name: fiap-postech-fastfood-orquestrador
          image: 731362576078.dkr.ecr.us-east-1.amazonaws.com/fiap_postech_fastfood_orquestrador:${IMAGE_TAG} #pegar uri do repositório ECR
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"  # Requisição de CPU inicial
              memory: "512Mi"
            limits:
              cpu: "500m"  # Limite de CPU
              memory: "1Gi"
          env:
            - name: ACCOUNT_ID
              value: "673847524989"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-postech-service-orquestrador
  namespace: fiap-pos-tech
spec:
  type: NodePort
  selector:
    app: fiap-postech-fastfood-orquestrador
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30011




